var data = [
{
  'restaurante':'Pollo Feliz',
  'imagen':'assets/images/food1.jpg',
  'mapa':'assets/images/mapa.jpg',
  'slogan':'comida para todos',
  'direccion':'Durango 18',
  'rango de precios':'$45 a $80', 
  'servicio':'servicio a domicilio',
},
{
  'restaurante':'Sabor',
  'imagen':'assets/images/food2.jpg',
  'mapa':'assets/images/mapa.jpg',
  'imagen':'assets/images/food2.jpg',
  'tipo':'tacos, tortas, refrescos',
  'direccion':'Durango 18',
  'rango de precios':'$45 a $80', 
  'servicio':'servicio a domicilio',
},
{
  'restaurante':'Don Polo',
  'imagen':'assets/images/food3.jpg',
  'mapa':'assets/images/mapa.jpg',
  'tipo':'alitas, hamburguesas, refrescos',
  'direccion':'Durango 18',
  'rango de precios':'$45 a $80', 
  'servicio':'servicio a domicilio',
},
{
  'restaurante':'La estaca',
  'imagen':'assets/images/food4.jpg',
  'mapa':'assets/images/mapa.jpg',
  'tipo':'tacos, tortas, refrescos',
  'direccion':'Durango 18',
  'rango de precios':'$45 a $80', 
  'servicio':'servicio a domicilio',
},
{
  'restaurante':'Camilos',
  'imagen':'assets/images/food5.jpg',
  'mapa':'../assets/images/mapa.jpg',
  'tipo':'alitas, tortas, cervezas',
  'direccion':'Durango 18',
  'rango de precios':'$45 a $80', 
  'servicio':'servicio a domicilio',
},
{
  'restaurante':'Molinos',
  'mapa':'assets/images/mapa.jpg',
  'imagen':'assets/images/food6.jpg',
  'tipo':'tacos, tortas, refrescos',
  'direccion':'Durango 18',
  'rango de precios':'$45 a $80', 
  'servicio':'servicio a domicilio',
},
{
  'restaurante':'El cabrito',
  'imagen':'assets/images/food7.jpg',
  'mapa':'../assets/images/mapa.jpg',
  'tipo':'carnes, pollo, cabrito, cortes, bebidas, vinos',
  'direccion':'Durango 18',
  'rango de precios':'$45 a $80', 
  'servicio':'servicio a domicilio',
},
{
  'restaurante':'Caminata de Alba',
  'imagen':'assets/images/food8.jpg',
  'mapa':'../assets/images/mapa.jpg',
  'tipo':'carnes, pollo, bebidas',
  'direccion':'Durango 18',
  'rango de precios':'$45 a $80', 
  'servicio':'servicio a domicilio',
},
{
  'restaurante':'Domino',
  'imagen':'assets/images/food9.jpg',
  'mapa':'../assets/images/mapa.jpg',
  'tipo':'carnes, pollo, mariscos, bebidas',
  'direccion':'Durango 18',
  'rango de precios':'$45 a $80', 
  'servicio':'servicio a domicilio',
},
{
  'restaurante':'El tacontento',
  'imagen':'assets/images/food10.jpg',
  'mapa':'../assets/images/mapa.jpg',
  'tipo':'tacos, hamburguesas, bebidas',
  'direccion':'Durango 18',
  'rango de precios':'$45 a $80', 
  'servicio':'servicio a domicilio',
},
];